### ISSUE TITLE
Dialog Loading for Infinite

### ISSUE THREAD

**Issue by VIRGO96** [DigitalPhantom/PhantomWeatherAndroid#14]
Hello the issue is that the Loading dialog box doesnot go away even internet is on and GPS is on its just keep on Loading 

![load](https://cloud.githubusercontent.com/assets/20814233/17689790/89b3b078-63a3-11e6-99f9-09360062dfb8.PNG)

**Comment by dute2** [comment]
same problem

**Comment by ynunez** [comment]
@VIRGO96 and @dute2 Sorry for the long delay, specially @VIRGO96  :)

Pull Request #15 should address that issue. Basically, the latest app was using reverse geolocation to get the weather for your current location and the steps were as follow:
1. Request GPS location from the device (this is what took so long)
2. Make a request to Google Maps API to request and address for the coordinates
3. Make a request to Yahoo Weather API to get weather data.

The current implementation uses the same flow with the exception that on the first step (GPS location) network location is used if available, network location is faster.

Hope that helps, let me know if I can help further

- The Phantom
