### ISSUE TITLE
Problem with some city/country combinations on some 5.1 devices

### ISSUE THREAD

**Issue by NikolajKaaOlsen** [DigitalPhantom/PhantomWeatherAndroid#4]
Hi,

I wrote regarding the problem on your youtube channel. 

The problem is that the app comes with an error if I use eg. European cities/countries. The error text is: Unparseable date: "Sat, 04 Jul 2015 12:00 pm CEST " (at offset 26) 

I have tried to run it on a Samsung Galaxy S6 with 5.1 firmware, a Asus TF101 Tablet with custom 5.1 firmware and on a Samsung tab pro with 4.4.2 firmware. The error only show up on the devices with lollipop.

I'm hoping that im giving you the correct logcat output. I have copied it to a text file and placed it on gogle drive:

https://drive.google.com/open?id=0BxTBghgUYk6lRW5iQjcycG5RdTA

Thank you,

Nikolaj Kaa Olsen

**Comment by ynunez** [comment]
This issue occurred due to some initial caching implementation that parsed the date without using the appropriate locale. This is not longer an issue since that caching implementation is not longer being used.
