### ISSUE TITLE
Just loading...

### ISSUE THREAD

**Issue by krajacic** [DigitalPhantom/PhantomWeatherAndroid#8]
I've try to run project on my OnePlus One but it's just loading... do you know maybe how to solve that problem?

![loading wrather](https://cloud.githubusercontent.com/assets/6814051/11424085/59286b7a-944a-11e5-9261-61b265874c2b.jpg)

edit: After more than 5min it showed Weather :dancer: 
Now it's okay :D

**Comment by VIRGO96** [comment]
Hello krajacic am having the same problem but waiting is not helping me i basically turned my app for 15 mins and the weather was not loaded neither the dialog box was removed if you have working code plz share i would appreciate that
